CREATE TABLE IF NOT EXISTS users
(
    id bigint generated by default as identity,
    uid VARCHAR(32) NOT NULL,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    user_name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL,
    active BOOLEAN DEFAULT true,
    role VARCHAR(16) NOT NULL,
    usr_created_date timestamp not null,
    usr_last_modified_date timestamp,
    PRIMARY KEY (id),
    UNIQUE (uid)
);